### ISSUE TITLE
Create pre-processing pipeline for qc and harmonization of studies for meta-analysis

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/META_ANALYSIS#31]
- [ ] Liftover to 38 as needed. Check resulting duplicate variants. Resolve duplicate variants if possible by allele frequency or rather remove both if cannot be unambiguously assigned

- [ ] Align summary stat alleles to reference genome (gnomad genomes). in case of ambiguous SNP, Infer correct allele order based on allele frequency. In case AF is close to 50% (e.g. > 45%), remove the variant.

- [ ] Left align and normalize alleles  (https://genome.sph.umich.edu/wiki/Vt#Normalization). Close issue #14 when done

- [ ] Plot allele frequencies of sumstats against allele frequency on gnomad (correct population, by default NFE). Flag variants to file that are significantly deviating from reference

**Comment by Fedja** [comment]
@juhis can you modify / add to the issue ^ ?

**Comment by juhaa** [comment]
> * [ ]  Liftover to 38 as needed. Check resulting duplicate variants. Resolve duplicate variants if possible by allele frequency or rather remove both if cannot be unambiguously assigned

We could add the duplicate variant checking directly to the liftover script under commons, e.g. report them in a separate file, as this most likely is of interest in many other analyses as well.

**Comment by Fedja** [comment]
> > * [ ]   Liftover to 38 as needed. Check resulting duplicate variants. Resolve duplicate variants if possible by allele frequency or rather remove both if cannot be unambiguously assigned
> 
> We could add the duplicate variant checking directly to the liftover script under commons, e.g. report them in a separate file, as this most likely is of interest in many other analyses as well.

yes good point that should be added indeed to the basic lift and written out!

**Comment by juhaa** [comment]
- [ ] Mahalonobis distance from AF vs AF_gnomAD to remove bad quality variants.

**Comment by Fedja** [comment]
@juhaa picard has liftover that does ref alignment and left alignment etc. https://gatk.broadinstitute.org/hc/en-us/articles/360036857991-LiftoverVcf-Picard

**Comment by Fedja** [comment]
All of these are done right and the issue can be closed? @juhaa
